export const HOUSES = [
  { id:"yellow", name:"Impala", colorLabel:"Yellow", color:"#f59e0b", bg:"#fffbeb", border:"#fcd34d" },
  { id:"red",    name:"Simba",  colorLabel:"Red",    color:"#ef4444", bg:"#fef2f2", border:"#fca5a5" },
  { id:"green",  name:"Twiga",  colorLabel:"Green",  color:"#22c55e", bg:"#f0fdf4", border:"#86efac" },
  { id:"blue",   name:"Chui",   colorLabel:"Blue",   color:"#3b82f6", bg:"#eff6ff", border:"#93c5fd" },
];

export const CLASSES = [
  "Y7/1","Y7/2","Y8/1","Y8/2","Y9/1","Y9/2","Y9/3",
  "Y10/1","Y10/2","Y10/3","Y11/1","Y11/2","Y12/1","Y12/2",
];

export const YEARS = ["Y7","Y8","Y9","Y10","Y11","Y12"];

export const KS_MAP = { Y7:"KS3",Y8:"KS3",Y9:"KS3",Y10:"KS4",Y11:"KS4",Y12:"KS5" };
export const getKS = g => KS_MAP[g?.split("/")?.[0]] || "";

export const KS_CLASSES = {
  ks3: CLASSES.filter(c => ["Y7","Y8","Y9"].includes(c.split("/")[0])),
  ks4: CLASSES.filter(c => ["Y10","Y11"].includes(c.split("/")[0])),
  ks5: CLASSES.filter(c => ["Y12"].includes(c.split("/")[0])),
};

export const ROLES = [
  { id:"admin",         label:"Admin" },
  { id:"principal",     label:"Principal" },
  { id:"dean_pastoral", label:"Dean of Pastoral" },
  { id:"dean_academic", label:"Dean of Academics" },
  { id:"discipline",    label:"Discipline Committee" },
  { id:"counselor",     label:"School Counselor" },
  { id:"safeguarding",  label:"Safeguarding Officer" },
  { id:"ks3",           label:"KS3 Coordinator" },
  { id:"ks4",           label:"KS4 Coordinator" },
  { id:"ks5",           label:"KS5 Coordinator" },
  { id:"teacher",       label:"Class Teacher" },
  { id:"student",       label:"Student" },
  { id:"parent",        label:"Parent" },
];

export const SENIOR = ["admin","principal","dean_pastoral","dean_academic","discipline","counselor","safeguarding"];
export const STAFF_ROLES = ["admin","principal","dean_pastoral","dean_academic","discipline","counselor","safeguarding","ks3","ks4","ks5","teacher"];

export const MILESTONES = [
  { pts:25,  badge:"Bronze",            icon:"🥉", color:"#92400e" },
  { pts:50,  badge:"Silver",            icon:"🥈", color:"#475569" },
  { pts:100, badge:"Gold",              icon:"🥇", color:"#b45309" },
  { pts:200, badge:"Principal's Award", icon:"🏅", color:"#7c3aed" },
  { pts:300, badge:"Platinum",          icon:"🏆", color:"#0e7490", ks5Only:true },
];

export const STAGES = [
  { pts:5,  stage:1, label:"Stage 1 — Pastoral Check-in",    color:"#f59e0b", who:"Class Teacher" },
  { pts:10, stage:2, label:"Stage 2 — KS Coordinator Review", color:"#f97316", who:"KS Coordinator" },
  { pts:20, stage:3, label:"Stage 3 — Pastoral Support Plan", color:"#ef4444", who:"Pastoral Lead" },
  { pts:35, stage:4, label:"Stage 4 — Leadership Referral",   color:"#dc2626", who:"Deputy Principal" },
  { pts:50, stage:5, label:"Stage 5 — Disciplinary Panel",    color:"#7f1d1d", who:"Principal / Committee" },
];

export const MATRIX = [
  { category:"Classroom & Academic", items:[
    { id:"ca_m1",  label:"Outstanding contribution to class discussion",       merit:2,  demerit:null },
    { id:"ca_m2",  label:"Full and focused engagement throughout lesson",      merit:1,  demerit:null },
    { id:"ca_m3",  label:"Exceptional quality of written or practical work",   merit:3,  demerit:null },
    { id:"ca_m4",  label:"Consistent homework completion over a full week",    merit:2,  demerit:null },
    { id:"ca_m5",  label:"Helping a peer understand a concept unprompted",     merit:2,  demerit:null },
    { id:"ca_m6",  label:"Creative or innovative approach to a task",          merit:3,  demerit:null },
    { id:"ca_m7",  label:"Taking intellectual risk — challenge question",      merit:2,  demerit:null },
    { id:"ca_m8",  label:"Outstanding Global Perspectives research",           merit:4,  demerit:null },
    { id:"ca_m9",  label:"Achieving a personal best in assessment",            merit:3,  demerit:null },
    { id:"ca_m10", label:"Demonstrating Cambridge learner attributes",         merit:2,  demerit:null },
    { id:"ca_m11", label:"Submitting work ahead of deadline, well-presented",  merit:1,  demerit:null },
    { id:"ca_m12", label:"Asking a deep enquiry-based question",               merit:1,  demerit:null },
    { id:"ca_d1",  label:"Arriving late to class without valid reason",        merit:null, demerit:-1 },
    { id:"ca_d2",  label:"Unprepared for lesson (no books/equipment)",         merit:null, demerit:-1 },
    { id:"ca_d3",  label:"Off-task, disengaged, or disrupting others",         merit:null, demerit:-2 },
    { id:"ca_d4",  label:"Eating or drinking in class without permission",     merit:null, demerit:-1 },
    { id:"ca_d5",  label:"Leaving class without permission",                   merit:null, demerit:-2 },
    { id:"ca_d6",  label:"Incomplete homework (first instance)",               merit:null, demerit:-1 },
    { id:"ca_d7",  label:"Persistent refusal to engage in learning",           merit:null, demerit:-3 },
    { id:"ca_d8",  label:"Writing on or defacing school materials",            merit:null, demerit:-2 },
    { id:"ca_d9",  label:"Academic dishonesty (copying, plagiarism)",          merit:null, demerit:-5 },
    { id:"ca_d10", label:"Cheating in a formal test or exam",                  merit:null, demerit:-8 },
  ]},
  { category:"Corridors & Common Areas", items:[
    { id:"co_m1", label:"Holding door open or assisting staff unprompted",     merit:2,  demerit:null },
    { id:"co_m2", label:"Picking up litter without being asked",               merit:2,  demerit:null },
    { id:"co_m3", label:"Representing SAA with pride to a visitor",            merit:3,  demerit:null },
    { id:"co_m4", label:"Calm, purposeful movement between lessons",           merit:1,  demerit:null },
    { id:"co_m5", label:"Supporting a peer who appears upset or lost",         merit:3,  demerit:null },
    { id:"co_m6", label:"Reporting a safety hazard to a staff member",         merit:2,  demerit:null },
    { id:"co_d1", label:"Running in corridors or stairwells",                  merit:null, demerit:-1 },
    { id:"co_d2", label:"Shouting or excessive noise in corridors",            merit:null, demerit:-1 },
    { id:"co_d3", label:"Pushing, jostling, or rough play in corridors",       merit:null, demerit:-2 },
    { id:"co_d4", label:"Loitering in restricted areas without permission",    merit:null, demerit:-1 },
    { id:"co_d5", label:"Littering in corridors or open areas",                merit:null, demerit:-2 },
    { id:"co_d6", label:"Defacing walls, doors or noticeboards",               merit:null, demerit:-4 },
    { id:"co_d7", label:"Vandalism of school property",                        merit:null, demerit:-8 },
    { id:"co_d8", label:"Entering out-of-bounds areas",                        merit:null, demerit:-2 },
  ]},
  { category:"Sports, PE & Extracurricular", items:[
    { id:"sp_m1", label:"Demonstrating sportsmanship and fair play",           merit:3,  demerit:null },
    { id:"sp_m2", label:"Outstanding effort in PE",                            merit:2,  demerit:null },
    { id:"sp_m3", label:"Representing school in a sports competition",         merit:5,  demerit:null },
    { id:"sp_m4", label:"Notable achievement in inter-school competition",     merit:4,  demerit:null },
    { id:"sp_m5", label:"Leading a warm-up or drill when invited",             merit:2,  demerit:null },
    { id:"sp_m6", label:"Consistent ECA attendance (per term)",                merit:2,  demerit:null },
    { id:"sp_m7", label:"Organising or helping run a school event",            merit:4,  demerit:null },
    { id:"sp_m8", label:"Supporting a struggling teammate",                    merit:2,  demerit:null },
    { id:"sp_m9", label:"Mentoring a junior student in sport (KS5)",           merit:4,  demerit:null },
    { id:"sp_d1", label:"Repeated failure to bring PE kit",                    merit:null, demerit:-2 },
    { id:"sp_d2", label:"Unsportsmanlike conduct — taunting or mocking",       merit:null, demerit:-3 },
    { id:"sp_d3", label:"Dangerous play — deliberate fouling",                 merit:null, demerit:-4 },
    { id:"sp_d4", label:"Refusing to follow coach instructions",               merit:null, demerit:-3 },
    { id:"sp_d5", label:"Causing deliberate injury during activity",           merit:null, demerit:-8 },
    { id:"sp_d6", label:"Leaving premises during ECA without permission",      merit:null, demerit:-5 },
    { id:"sp_d7", label:"Using sports equipment dangerously unsupervised",     merit:null, demerit:-2 },
    { id:"sp_d8", label:"Abusing or damaging sports equipment",                merit:null, demerit:-4 },
  ]},
  { category:"Interpersonal Relationships", items:[
    { id:"ip_m1", label:"Resolving a disagreement calmly without staff",       merit:3,  demerit:null },
    { id:"ip_m2", label:"Standing up for a peer being excluded unfairly",      merit:4,  demerit:null },
    { id:"ip_m3", label:"Welcoming and supporting a new student",              merit:3,  demerit:null },
    { id:"ip_m4", label:"Consistent kindness and consideration",               merit:2,  demerit:null },
    { id:"ip_m5", label:"Proactively reporting a safeguarding concern",        merit:3,  demerit:null },
    { id:"ip_m6", label:"Acting as peer mentor or tutor",                      merit:4,  demerit:null },
    { id:"ip_m7", label:"Treating all staff and visitors with courtesy",       merit:2,  demerit:null },
    { id:"ip_m8", label:"Contributing positively to a group project",          merit:2,  demerit:null },
    { id:"ip_m9", label:"Demonstrating empathy during a difficult situation",  merit:3,  demerit:null },
    { id:"ip_d1", label:"Rude or disrespectful language to a peer",            merit:null, demerit:-2 },
    { id:"ip_d2", label:"Rude or disrespectful language to a staff member",    merit:null, demerit:-4 },
    { id:"ip_d3", label:"Deliberate exclusion or social isolation",            merit:null, demerit:-3 },
    { id:"ip_d4", label:"Low-level verbal bullying (name-calling)",            merit:null, demerit:-4 },
    { id:"ip_d5", label:"Sustained or repeated bullying",                      merit:null, demerit:-10 },
    { id:"ip_d6", label:"Physical aggression — pushing/shoving (no injury)",   merit:null, demerit:-5 },
    { id:"ip_d7", label:"Physical assault causing injury",                     merit:null, demerit:-15 },
    { id:"ip_d8", label:"Threatening behaviour or intimidation",               merit:null, demerit:-10 },
    { id:"ip_d9", label:"Cyberbullying or online harassment",                  merit:null, demerit:-10 },
    { id:"ip_d10",label:"Public display of romantic affection",                merit:null, demerit:-2 },
    { id:"ip_d11",label:"Discrimination based on race, gender or religion",    merit:null, demerit:-15 },
    { id:"ip_d12",label:"Theft from a peer or the school",                     merit:null, demerit:-10 },
  ]},
  { category:"School Rules, Safety & Property", items:[
    { id:"sr_m1", label:"Full term of 100% punctuality",                       merit:5,  demerit:null },
    { id:"sr_m2", label:"Consistent exemplary uniform standard (per term)",    merit:3,  demerit:null },
    { id:"sr_m3", label:"Reporting a safety hazard immediately",               merit:2,  demerit:null },
    { id:"sr_m4", label:"Returning borrowed equipment in excellent condition",  merit:2,  demerit:null },
    { id:"sr_m5", label:"Perfect attendance for a full term",                  merit:5,  demerit:null },
    { id:"sr_m6", label:"Outstanding conduct on an off-site trip",             merit:4,  demerit:null },
    { id:"sr_m7", label:"Caring for shared spaces",                            merit:1,  demerit:null },
    { id:"sr_m8", label:"Helping to set up or clear away for school event",    merit:3,  demerit:null },
    { id:"sr_d1", label:"Arriving late to school without valid reason",        merit:null, demerit:-1 },
    { id:"sr_d2", label:"Unauthorised absence from school",                    merit:null, demerit:-3 },
    { id:"sr_d3", label:"Uniform non-compliance (minor)",                      merit:null, demerit:-1 },
    { id:"sr_d4", label:"Persistent uniform non-compliance after warnings",    merit:null, demerit:-3 },
    { id:"sr_d5", label:"Chewing gum on school premises",                      merit:null, demerit:-1 },
    { id:"sr_d6", label:"Littering on school grounds",                         merit:null, demerit:-2 },
    { id:"sr_d7", label:"Using mobile phone during class (KS3/4)",             merit:null, demerit:-2 },
    { id:"sr_d8", label:"Using mobile phone during class (KS5, after warning)",merit:null, demerit:-1 },
    { id:"sr_d9", label:"Bringing a prohibited item to school",                merit:null, demerit:-4 },
    { id:"sr_d10",label:"Misuse of school digital platforms",                  merit:null, demerit:-4 },
    { id:"sr_d11",label:"Leaving premises without authorised exit slip",       merit:null, demerit:-3 },
    { id:"sr_d12",label:"Running in or around the school building",            merit:null, demerit:-1 },
    { id:"sr_d13",label:"Playing in wet or hazardous conditions",              merit:null, demerit:-2 },
    { id:"sr_d14",label:"Substance use on premises",                           merit:null, demerit:-15 },
    { id:"sr_d15",label:"Possession of dangerous items or weapons",            merit:null, demerit:-15 },
  ]},
  { category:"Dining Hall & Shared Spaces", items:[
    { id:"di_m1", label:"Queuing patiently, allowing younger students first",  merit:2,  demerit:null },
    { id:"di_m2", label:"Clearing table and leaving dining area tidy",         merit:2,  demerit:null },
    { id:"di_m3", label:"Polite and patient with dining staff",                merit:1,  demerit:null },
    { id:"di_m4", label:"Assisting a student with difficulty in queue",        merit:2,  demerit:null },
    { id:"di_d1", label:"Queue jumping or aggressive queuing",                 merit:null, demerit:-2 },
    { id:"di_d2", label:"Eating or drinking in class or corridors",            merit:null, demerit:-1 },
    { id:"di_d3", label:"Leaving dining area untidy deliberately",             merit:null, demerit:-2 },
    { id:"di_d4", label:"Wasting food deliberately",                           merit:null, demerit:-1 },
    { id:"di_d5", label:"Ordering food from outside without SLT permission",   merit:null, demerit:-2 },
    { id:"di_d6", label:"Talking to strangers at the gate",                    merit:null, demerit:-3 },
  ]},
  { category:"Digital Citizenship & Technology", items:[
    { id:"dt_m1", label:"Using school platforms responsibly, helping peers",   merit:2,  demerit:null },
    { id:"dt_m2", label:"Citing AI tools or online sources correctly",         merit:2,  demerit:null },
    { id:"dt_m3", label:"Reporting inappropriate digital content",             merit:3,  demerit:null },
    { id:"dt_m4", label:"Producing creative digital project beyond minimum",   merit:3,  demerit:null },
    { id:"dt_m5", label:"Responsible use of technology in class project",      merit:2,  demerit:null },
    { id:"dt_d1", label:"Using device for non-academic purposes in lessons",   merit:null, demerit:-2 },
    { id:"dt_d2", label:"Accessing inappropriate websites on school network",  merit:null, demerit:-4 },
    { id:"dt_d3", label:"Recording staff or students without consent",         merit:null, demerit:-5 },
    { id:"dt_d4", label:"Sharing another student's image without consent",     merit:null, demerit:-8 },
    { id:"dt_d5", label:"Cyberbullying",                                       merit:null, demerit:-10 },
    { id:"dt_d6", label:"Bypassing school internet filter or firewall",        merit:null, demerit:-5 },
    { id:"dt_d7", label:"Submitting unacknowledged AI-generated work",         merit:null, demerit:-5 },
  ]},
  { category:"Leadership & Community Service", items:[
    { id:"lc_m1", label:"School leadership role (per term)",                   merit:10, demerit:null },
    { id:"lc_m2", label:"Organising or leading a school event or charity",     merit:6,  demerit:null },
    { id:"lc_m3", label:"Completing a structured community service project",   merit:8,  demerit:null },
    { id:"lc_m4", label:"Leading a presentation at assembly",                  merit:4,  demerit:null },
    { id:"lc_m5", label:"Serving as Student Ambassador or tour guide",         merit:4,  demerit:null },
    { id:"lc_m6", label:"Contributing to school newsletter or magazine",       merit:3,  demerit:null },
    { id:"lc_m7", label:"Notable result in national or international competition", merit:8, demerit:null },
    { id:"lc_m8", label:"Sixth Form Peer Mentor, per term (KS5)",              merit:6,  demerit:null },
    { id:"lc_m9", label:"Initiating an environmental or sustainability project",merit:6, demerit:null },
  ]},
];

export const DEFAULT_BRAND = {
  schoolName: "St. Austin's Academy",
  motto: "Dare to Be",
  logoUrl: "",
  primaryColor: "#4a1a7a",
  secondaryColor: "#6b21a8",
  accentColor: "#e9d5ff",
  buttonColor: "#6b21a8",
  highlightColor: "#f3e8ff",
  borderColor: "#c4b5fd",
  address: "Nairobi, Kenya",
  phone: "", email: "", website: "",
  facebook: "", twitter: "", instagram: "", whatsapp: "",
};
